spring:
  datasource:
    url: jdbc:mysql://localhost/the-cashier?useSSL=false
    username: root
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8878